Remove GNU coreutils requirement. Refactor to main $@.

diff --git a/libexec/jlenv b/libexec/jlenv
--- a/libexec/jlenv
+++ b/libexec/jlenv
@@ -2,7 +2,7 @@
 #
 # Summary: Set environment variables then invoke jlenv commands.
 #
-# Usage: jlenv [--sh|--no-sh] <command> [<command-options>]
+# Usage: jlenv [options] <command> [<command-options>]
 #
 # Sets the environemnt variables then invokes the given command and its options.
 
@@ -32,7 +32,7 @@ function script_trap_err() {
 
     # Validate any provided exit code
     if [[ ${1-} =~ ^[0-9]+$ ]]; then
-        exit_code="$1"
+        exit_code="${1}"
     fi
 
     # Output debug data if in Cron mode
@@ -42,25 +42,26 @@ function script_trap_err() {
             exec 1>&3 2>&4
         fi
 
-        # Print basic debugging information
+        # Restore terminal colours
         printf '%b\n' "$ta_none"
-        printf '***** Abnormal termination of script *****\n'
-        printf 'Script Path:            %s\n' "$script_path"
-        printf 'Script Parameters:      %s\n' "$script_params"
-        printf 'Script Exit Code:       %s\n' "$exit_code"
+        # Print basic debugging information
+        printf 'jlenv:  ***** Abnormal termination of script *****\n'
+        printf 'jlenv:  Script Path:            %s\n' "$script_path"
+        printf 'jlenv:  Script Parameters:      %s\n' "$script_params"
+        printf 'jlenv:  Script Exit Code:       %s\n' "$exit_code"
 
         # Print the script log if we have it. It's possible we may not if we
         # failed before we even called cron_init(). This can happen if bad
         # parameters were passed to the script so we bailed out very early.
         if [[ -n ${script_output-} ]]; then
-            printf 'Script Output:\n\n%s' "$(cat "$script_output")"
+            printf 'jlenv:  Script Output:\n\n%s' "$(cat "$script_output")"
         else
-            printf 'Script Output:          None (failed before log init)\n'
+            printf 'jlenv:  Script Output:          None (failed before log init)\n'
         fi
     fi
 
     # Exit with failure status
-    exit "$exit_code"
+    exit "${exit_code}"
 }
 
 
@@ -68,7 +69,7 @@ function script_trap_err() {
 # ARGS: None
 # OUTS: None
 function script_trap_exit() {
-    cd "$orig_cwd"
+    cd "${orig_cwd:-}"
 
     # Remove Cron mode script log
     if [[ -n ${cron-} && -f ${script_output-} ]]; then
@@ -81,7 +82,7 @@ function script_trap_exit() {
     fi
 
     # Restore terminal colours
-    printf '%b' "$ta_none"
+    printf '%b' "${ta_none:-}"
 }
 
 
@@ -91,21 +92,21 @@ function script_trap_exit() {
 # OUTS: None
 function script_exit() {
     if [[ $# -eq 1 ]]; then
-        printf '%s\n' "$1"
+        printf 'jlenv:  %s\n' "${1}"
         exit 0
     fi
 
     if [[ ${2-} =~ ^[0-9]+$ ]]; then
-        printf '%b\n' "$1"
+        printf 'jlenv:  %b\n' "${1}"
         # If we've been provided a non-zero exit code run the error trap
         if [[ $2 -ne 0 ]]; then
-            script_trap_err "$2"
+            script_trap_err "${2}"
         else
             exit 0
         fi
     fi
 
-    script_exit 'Missing required argument to script_exit()!' 2
+    script_exit 'Missing required argument to $(script_exit)' 2
 }
 
 
@@ -277,9 +278,9 @@ function pretty_print() {
 
     # Print message & reset text attributes
     if [[ -n ${3-} ]]; then
-        printf '%s%b' "$1" "$ta_none"
+        printf 'jlenv:  %s%b' "$1" "$ta_none"
     else
-        printf '%s%b\n' "$1" "$ta_none"
+        printf 'jlenv:  %s%b\n' "$1" "$ta_none"
     fi
 }
 
@@ -359,9 +360,9 @@ function check_superuser() {
         superuser=true
     elif [[ -z ${1-} ]]; then
         if check_binary sudo; then
-            verbose_print 'Sudo: Updating cached credentials ...'
+            verbose_print 'sudo: Updating cached credentials ...'
             if ! sudo -v; then
-                verbose_print "Sudo: Couldn't acquire credentials ..." \
+                verbose_print "sudo: Couldn't acquire credentials ..." \
                               "${fg_red-}"
             else
                 local test_euid
@@ -407,17 +408,20 @@ function run_as_root() {
 }
 
 
-# DESC: Usage help
+# DESC: Full jlenv usage help.
 # ARGS: None
-# OUTS: None
+# OUTS: Help text.
 function script_usage() {
+    command jlenv---version
     cat << EOF
-Usage:
+Options to jlenv:
      -h|--help                  Displays this help
      -v|--verbose               Displays verbose output
     -nc|--no-colour             Disables colour output
     -cr|--cron                  Run silently unless we encounter an error
+
 EOF
+    command jlenv-help
 }
 
 
@@ -426,6 +430,11 @@ EOF
 # OUTS: Variables indicating command-line parameters and options
 function parse_params() {
     local param
+    if [[ $# -eq 0 ]]
+    then
+      script_usage
+      exit 1
+    fi
     while [[ $# -gt 0 ]]; do
         param="$1"
         shift
@@ -435,7 +444,7 @@ function parse_params() {
                 exit 0
                 ;;
             -v|--verbose)
-                verbose=true
+                verbose_setup
                 ;;
             -nc|--no-colour)
                 no_colour=true
@@ -444,12 +453,215 @@ function parse_params() {
                 cron=true
                 ;;
             *)
-                script_exit "Invalid parameter was provided: $param" 2
+                # Now process jlenv commands and their options.
+                command_path="$(command -v "jlenv-$param" || true)"
+                [ -n "$command_path" ] || script_exit "No such command: \$($param)" 2
+
+                if [[ $# -ge 1 ]]; 
+                then 
+                  arg="${1-}"
+                  shift 1
+                fi
+
+                if [ "${1-}" = --help ]; then
+                  if [[ "$param" == "sh-"* ]]; then
+                    echo "jlenv help \"$param\""
+                  else
+                    exec jlenv-help "$param"
+                  fi
+                else
+                  exec "$command_path" "${arg-}" "$@"
+                fi
                 ;;
         esac
     done
 }
 
+# DESC: Set environement variable default values.
+#       Variables should not be referenced using ${variable:-default}.
+#       Variables should not be tested using:
+#         1. [ -n "${variable}" ]
+#         2. [ -z "${variable}"]
+#       Instead test for explicit values: 
+#         [ "${variable}" = "value" ]
+# ARGS: None.
+# OUTS: None.
+script_defaults() {
+  setup_jlenv_debug
+  # setup_readlink
+  setup_jlenv_root
+  setup_jlenv_dir
+  shopt -s nullglob
+  setup_path
+  setup_jlenv_hook_path
+  shopt -u nullglob
+}
+
+# DESC: Setup the JLENV_DEBUG environment variable.  Default value is no-debug
+#       if not already set. Values:
+#         1: Debug output
+#         0: No-debug output
+# ARGS: None.
+# OUTS: None.
+setup_jlenv_debug() {
+  case ${JLENV_DEBUG:-0} in
+    0) # Disable tracing
+      set +o xtrace          # Do not trace the execution of the script (no-debug)
+      ;;
+    1) # Enable tracing
+      set -o xtrace          # Trace the execution of the script (debug)
+      ;;
+    *) # Disable tracing
+      set +x
+      ;;
+  esac
+}
+
+# DESC: Setup the JLENV_ROOT environment variable.  Default value is set if not
+#       already set.
+# ARGS: None.
+# OUTS: None.
+setup_jlenv_root() {
+  # test if the variable is set and non-empty
+  if [ "${JLENV_ROOT:-setdefault}" = "setdefault" ]; then
+    JLENV_ROOT="${HOME}/.jlenv"
+  else
+    JLENV_ROOT="${JLENV_ROOT%/}"
+  fi
+  export JLENV_ROOT
+}
+
+# DESC: Setup the JLENV_DIR environment variable.
+# ARGS: None.
+# OUTS: None.
+setup_jlenv_dir() {
+  # test if the variable is set and non-empty
+  if [ "${JLENV_DIR:-setdefault}" = "setdefault" ]; then
+    JLENV_DIR="$PWD"
+  else
+    cd "${JLENV_DIR}" 2>/dev/null || script_exit "Cannot change working directory to \$(${JLENV_DIR})" 1
+    JLENV_DIR="$PWD"
+    cd "$OLDPWD"
+  fi
+  export JLENV_DIR
+}
+
+# DESC: Setup the PATH environment variable.
+# ARGS: None.
+# OUTS: None.
+setup_path() {
+  bin_path="$(abs_dirname "$0")"
+  for plugin_bin in "${JLENV_ROOT}/plugins/"*/bin; do
+    PATH="${plugin_bin}:${PATH}"
+  done
+  export PATH="${bin_path}:${PATH}"
+}
+
+# DESC: Setup the JLENV_HOOK_PATH environment variable.
+# ARGS: None.
+# OUTS: None.
+setup_jlenv_hook_path() {
+  bin_path="$(abs_dirname "$0")"
+  JLENV_HOOK_PATH="${JLENV_HOOK_PATH:-}:${JLENV_ROOT}/jlenv.d"
+  if [ "${bin_path%/*}" != "$JLENV_ROOT" ]; then
+    # Add jlenv's own `jlenv.d` unless jlenv was cloned to JLENV_ROOT
+    JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${bin_path%/*}/jlenv.d"
+  fi
+  JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:/usr/local/etc/jlenv.d:/etc/jlenv.d:/usr/lib/jlenv/hooks"
+  for plugin_hook in "${JLENV_ROOT}/plugins/"*/etc/jlenv.d; do
+    JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${plugin_hook}"
+  done
+  JLENV_HOOK_PATH="${JLENV_HOOK_PATH#:}"
+  export JLENV_HOOK_PATH
+}
+
+# DESC: Setup debug/verbose output.
+# ARGS: None.
+# OUTS: None.
+verbose_setup() {
+  verbose=true
+  export JLENV_DEBUG=1
+  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
+  set -o xtrace          # Trace the execution of the script (debug)
+}
+
+# DESC: Recursively follow symlinks in every component of the given file name.
+#       All but the last component must exist.
+# ARGS: $@ (required): The file to be dereferenced.
+# OUTS: Value of a canonical file name
+resolve_link() {
+  res=$(command readlink --canonicalize "$1")
+  echo $res
+}
+
+# DESC: Generate absolute directory path from relative path.
+# ARGS: $1 (required): relative filename
+# OUTS: Absolute path
+# NOTE: Does not require GNU coreutils' $(readlink) or $(realpath).
+#       Usage examples, assume inside /parent/cur
+#       abs_dirname file.txt              => /parent/cur
+#       abs_dirname .                     => /parent/cur
+#       abs_dirname ..                    => /parent
+#       abs_dirname ../dir/file.txt       => /parent/dir
+#       abs_dirname /dir/../dir2/file.txt => /parent/dir2
+#       abs_dirname ../dir/../dir2        => /parent/dir2          # anything cd can handle
+#       abs_dirname doesnotexist          =>                       # empty result if file/dir does not exist
+#       abs_dirname /file.txt             => /                     # handle absolute path input
+# REFS: 
+#       https://stackoverflow.com/a/21951256/152860
+#       https://stackoverflow.com/a/7577209/152860
+#       https://stackoverflow.com/a/15780028/152860
+#       https://stackoverflow.com/a/23002317/152860
+abs_dirname(){
+  local thePath
+  declare -a outp
+  if [[ ! "$1" =~ ^/ ]];then
+    thePath="$PWD/$1"
+  else
+    thePath="$1"
+  fi
+  # Parse the path.  Result is possibly a file name.
+  fn=$(
+      echo "$thePath"|(
+      IFS=/
+      read -a parr
+      for i in "${parr[@]}";do
+        case "$i" in
+        ''|.) continue ;;
+        ..)
+          len=$(count_array "${outp[@]+"${outp[@]}"}")
+          if ((len==0));then
+            continue
+          else
+            unset -v 'outp[ $((len-1)) ]'
+          fi
+          ;;
+        *)
+          # Undefined variable error workaround for:
+          # len=${#outp[@]}
+          #
+          # 1. https://stackoverflow.com/a/7577209/152860
+          # Use ${outp[@]+"${outp[@]}"} instead of "${outp[@]}"
+          len=$(count_array "${outp[@]+"${outp[@]}"}")
+          outp[$len]="$i"
+          ;;
+        esac
+      done
+      echo /"${outp[*]}"
+    )
+  )
+  if [ -f "${fn}" ] 
+  then
+    # file
+    echo "$(cd "$(dirname "${fn}")"; pwd)"
+  else
+    # folder
+    echo "${fn}"
+  fi
+}
+
+# https://stackoverflow.com/a/15780028/152860
+count_array() { echo $# ; };
 
 # DESC: Main control flow
 # ARGS: $@ (optional): Arguments provided to the script
@@ -457,6 +669,8 @@ function parse_params() {
 function main() {
     trap script_trap_err ERR
     trap script_trap_exit EXIT
+
+    script_defaults
 
     script_init "$@"
     parse_params "$@"
@@ -470,114 +684,3 @@ function main() {
 #####################################################################
 
 main "$@"
-
-unset CDPATH
-
-if [ "$1" = "--debug" ]; then
-  export JLENV_DEBUG=1
-  shift
-fi
-
-if [ -n "$JLENV_DEBUG" ]; then
-  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
-  set -o xtrace          # Trace the execution of the script (debug)
-fi
-
-abort() {
-  { if [ "$#" -eq 0 ]; then cat -
-    else echo "jlenv: $*"
-    fi
-  } >&2
-  exit 1
-}
-
-READLINK=$(type -p greadlink readlink | head -1)
-[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
-
-resolve_link() {
-  $READLINK "$1"
-}
-
-abs_dirname() {
-  local cwd="$PWD"
-  local path="$1"
-
-  while [ -n "$path" ]; do
-    cd "${path%/*}"
-    local name="${path##*/}"
-    path="$(resolve_link "$name" || true)"
-  done
-
-  pwd
-  cd "$cwd"
-}
-
-if [ -z "${JLENV_ROOT}" ]; then
-  JLENV_ROOT="${HOME}/.jlenv"
-else
-  JLENV_ROOT="${JLENV_ROOT%/}"
-fi
-export JLENV_ROOT
-
-if [ -z "${JLENV_DIR}" ]; then
-  JLENV_DIR="$PWD"
-else
-  cd "$JLENV_DIR" 2>/dev/null || abort "cannot change working directory to \$($JLENV_DIR)"
-  JLENV_DIR="$PWD"
-  cd "$OLDPWD"
-fi
-export JLENV_DIR
-
-
-shopt -s nullglob
-
-bin_path="$(abs_dirname "$0")"
-for plugin_bin in "${JLENV_ROOT}/plugins/"*/bin; do
-  PATH="${plugin_bin}:${PATH}"
-done
-export PATH="${bin_path}:${PATH}"
-
-JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${JLENV_ROOT}/jlenv.d"
-if [ "${bin_path%/*}" != "$JLENV_ROOT" ]; then
-  # Add jlenv's own `jlenv.d` unless jlenv was cloned to JLENV_ROOT
-  JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${bin_path%/*}/jlenv.d"
-fi
-JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:/usr/local/etc/jlenv.d:/etc/jlenv.d:/usr/lib/jlenv/hooks"
-for plugin_hook in "${JLENV_ROOT}/plugins/"*/etc/jlenv.d; do
-  JLENV_HOOK_PATH="${JLENV_HOOK_PATH}:${plugin_hook}"
-done
-JLENV_HOOK_PATH="${JLENV_HOOK_PATH#:}"
-export JLENV_HOOK_PATH
-
-shopt -u nullglob
-
-
-command="$1"
-case "$command" in
-"" )
-  { jlenv---version
-    jlenv-help
-  } | abort
-  ;;
--v | --version )
-  exec jlenv---version
-  ;;
--h | --help )
-  exec jlenv-help
-  ;;
-* )
-  command_path="$(command -v "jlenv-$command" || true)"
-  [ -n "$command_path" ] || abort "no such command \$($command)"
-
-  shift 1
-  if [ "$1" = --help ]; then
-    if [[ "$command" == "sh-"* ]]; then
-      echo "jlenv help \"$command\""
-    else
-      exec jlenv-help "$command"
-    fi
-  else
-    exec "$command_path" "$@"
-  fi
-  ;;
-esac
