Tests updated to bats-core, bats-assert, bats-file, bats-support and bats-mock (#1)
* Add doc: why jlenv
* Cleanup simplify
* Ignore editor settings.
* Update License.
* Add github-pages jekyll config.
* Add toc generator for Markdown files.
* Simplify Readme.  Point to documentation site.
* Add authoring plugin doc.
* Add plugins doc.
* Add edit path doc.
* Add deploying jlenv doc
* Add Unix shel init doc.
* Add understanding binstubs doc.
* Add FAQ troubleshooting doc.
* Add how it works doc
* Add command reference doc
* Add readme.md doc
* Use Julia version numbers.
* Fix tests
* Tweak doc references.
* Add theme.
* Add home links.  Fix reference links.
* Fix header link.
* Fix cookbook description.
* Add available Julia list update doc.
* Port tests to bats-core, bats-assert, bats-file, bats-support, bats-mock.
* Change command \`..' to $(...) in text strings.  See SC2091, SC2092.
* Add Julia v prefix to version numbers.  Fix HEREDOC statements.
* Fix tests breaking due to mktmp paths.
* Refactor helper script. Fix tests for mktmp locations.
* Travis realpath issue.
* Remove realpath dependency.
* Remove unsupported behaviour example.
* Simplfy readpath: Add GNU CoreUtils requirement.
* Use readlink. Remove realpath.
* Fixed string.
* Fix sytem prefix test.

diff --git a/libexec/jlenv b/libexec/jlenv
--- a/libexec/jlenv
+++ b/libexec/jlenv
@@ -20,35 +20,26 @@ abort() {
   exit 1
 }
 
-if enable -f "${BASH_SOURCE%/*}"/../libexec/jlenv-realpath.dylib realpath 2>/dev/null; then
-  abs_dirname() {
-    local path="$(realpath "$1")"
-    echo "${path%/*}"
-  }
-else
-  [ -z "$JLENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"
+READLINK=$(type -p greadlink readlink | head -1)
+[ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
 
-  READLINK=$(type -p greadlink readlink | head -1)
-  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
+resolve_link() {
+  $READLINK "$1"
+}
 
-  resolve_link() {
-    $READLINK "$1"
-  }
+abs_dirname() {
+  local cwd="$PWD"
+  local path="$1"
 
-  abs_dirname() {
-    local cwd="$PWD"
-    local path="$1"
+  while [ -n "$path" ]; do
+    cd "${path%/*}"
+    local name="${path##*/}"
+    path="$(resolve_link "$name" || true)"
+  done
 
-    while [ -n "$path" ]; do
-      cd "${path%/*}"
-      local name="${path##*/}"
-      path="$(resolve_link "$name" || true)"
-    done
-
-    pwd
-    cd "$cwd"
-  }
-fi
+  pwd
+  cd "$cwd"
+}
 
 if [ -z "${JLENV_ROOT}" ]; then
   JLENV_ROOT="${HOME}/.jlenv"
@@ -60,7 +51,7 @@ export JLENV_ROOT
 if [ -z "${JLENV_DIR}" ]; then
   JLENV_DIR="$PWD"
 else
-  cd "$JLENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$JLENV_DIR'"
+  cd "$JLENV_DIR" 2>/dev/null || abort "cannot change working directory to \$($JLENV_DIR)"
   JLENV_DIR="$PWD"
   cd "$OLDPWD"
 fi
@@ -105,7 +96,7 @@ case "$command" in
   ;;
 * )
   command_path="$(command -v "jlenv-$command" || true)"
-  [ -n "$command_path" ] || abort "no such command \`$command'"
+  [ -n "$command_path" ] || abort "no such command \$($command)"
 
   shift 1
   if [ "$1" = --help ]; then
