Remove realpath dependency.

diff --git a/libexec/jlenv-hooks b/libexec/jlenv-hooks
--- a/libexec/jlenv-hooks
+++ b/libexec/jlenv-hooks
@@ -22,10 +22,10 @@ if [ -z "$JLENV_COMMAND" ]; then
 fi
 
 if ! enable -f "${BASH_SOURCE%/*}"/jlenv-realpath.dylib realpath 2>/dev/null; then
-  if [ -n "$JLENV_NATIVE_EXT" ]; then
-    echo "jlenv: failed to load \`realpath' builtin" >&2
-    exit 1
-  fi
+  # if [ -n "$JLENV_NATIVE_EXT" ]; then
+  #   echo "jlenv: failed to load \`realpath' builtin" >&2
+  #   exit 1
+  # fi
 READLINK=$(type -p greadlink readlink | head -1)
 if [ -z "$READLINK" ]; then
   echo "jlenv: cannot find readlink - are you missing GNU coreutils?" >&2
diff --git a/libexec/jlenv-versions b/libexec/jlenv-versions
--- a/libexec/jlenv-versions
+++ b/libexec/jlenv-versions
@@ -28,10 +28,10 @@ done
 versions_dir="${JLENV_ROOT}/versions"
 
 if ! enable -f "${BASH_SOURCE%/*}"/jlenv-realpath.dylib realpath 2>/dev/null; then
-  if [ -n "$JLENV_NATIVE_EXT" ]; then
-    echo "jlenv: failed to load \`realpath' builtin" >&2
-    exit 1
-  fi
+  # if [ -n "$JLENV_NATIVE_EXT" ]; then
+  #   echo "jlenv: failed to load \`realpath' builtin" >&2
+  #   exit 1
+  # fi
 
   READLINK=$(type -p greadlink readlink | head -1)
   if [ -z "$READLINK" ]; then
