Change command \`..' to $(...) in text strings.  See SC2091, SC2092.

diff --git a/libexec/jlenv b/libexec/jlenv
--- a/libexec/jlenv
+++ b/libexec/jlenv
@@ -26,7 +26,7 @@ if enable -f "${BASH_SOURCE%/*}"/../libexec/jlenv-realpath.dylib realpath 2>/dev
     echo "${path%/*}"
   }
 else
-  [ -z "$JLENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"
+  [ -z "$JLENV_NATIVE_EXT" ] || abort "failed to load \$(realpath) builtin"
 
   READLINK=$(type -p greadlink readlink | head -1)
   [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"
@@ -60,7 +60,7 @@ export JLENV_ROOT
 if [ -z "${JLENV_DIR}" ]; then
   JLENV_DIR="$PWD"
 else
-  cd "$JLENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$JLENV_DIR'"
+  cd "$JLENV_DIR" 2>/dev/null || abort "cannot change working directory to \$($JLENV_DIR)"
   JLENV_DIR="$PWD"
   cd "$OLDPWD"
 fi
@@ -105,7 +105,7 @@ case "$command" in
   ;;
 * )
   command_path="$(command -v "jlenv-$command" || true)"
-  [ -n "$command_path" ] || abort "no such command \`$command'"
+  [ -n "$command_path" ] || abort "no such command \$($command)"
 
   shift 1
   if [ "$1" = --help ]; then
